### ISSUE TITLE
There were errors when initializing

### ISSUE THREAD

**Issue by DavidRL77** [LFGaming/Discord_rich_presence_noita#2]
The first time I tried it it worked fine, but after one game it just stopped loading properly
![2022-04-30 14_05_27-Window](https://user-images.githubusercontent.com/89250604/166104816-b634f7d6-6324-408c-8784-7dff29c483f6.png)
.

**Comment by LFGaming** [comment]
Hmm,, I'll take a look. anything you added or removed? like other mods for example?

**Comment by DavidRL77** [comment]
The problem is that when downloading it from github, it adds that '-main' at the end, and makes it so it can't find the folder. I removed that and it worked fine

**Comment by LFGaming** [comment]
Ah okay,, I'll take a look at that then, thanks

**Comment by LFGaming** [comment]
I don't get -main behind my downloads when downloading.

**Comment by DavidRL77** [comment]
When you download it from here
![image](https://user-images.githubusercontent.com/89250604/169340213-1908f912-ab4f-4601-84b5-844d15862987.png)

**Comment by LFGaming** [comment]
oh there,, yes thats because you download the github page,, when using the releases tab on the right it does not have the -main behind it,, hope this helps?

**Comment by DavidRL77** [comment]
Ok thanks
