### ISSUE TITLE
Adding a disclaimer in the readme.md

### ISSUE THREAD

**Issue by Synaelle** [LFGaming/Discord_rich_presence_noita#3]
At first the mod wasn't working for me, and that's because the name of the folder was wrong for me. Since your mod doesn't come with the folder, I thought I just create mine with a name like DiscordRPC and it wasn't working. 

So you may add that we need absolutely to have the mod in a folder named "Discord_rich_presence_noita"
I don't think anyone could figured out, I checked logs to find my mistake.

**Comment by LFGaming** [comment]
well, if you follow the steps in the Readme, then it says to download it from the releases tab, and unzip the file,, if you do that you get a folder called Discord_rich_presence_noita.
But Ill fix the Readme to make it more clear

**Comment by Synaelle** [comment]
Yeah but extracting a zip isn't just a button. You have many ways to extract an archive.

**Comment by LFGaming** [comment]
I've added that it has to be called "Discord_rich_presence_noita" is that good enough for you, or do you want it to be changed more?
